// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFV2mgyVksQiUgtE2SrXCr6AYHW0y_m_0',
    appId: '1:17043717885:web:24165355616bef7cc9c894',
    messagingSenderId: '17043717885',
    projectId: 'denote-bb303',
    authDomain: 'denote-bb303.firebaseapp.com',
    storageBucket: 'denote-bb303.appspot.com',
    measurementId: 'G-Z42KKSVRB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC_b7U-uafQ5PzIqgw-M9CO8hZAoLJqzs',
    appId: '1:17043717885:android:f97fff2d819cc856c9c894',
    messagingSenderId: '17043717885',
    projectId: 'denote-bb303',
    storageBucket: 'denote-bb303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn3FyXyxPzDF4KKnm2vP0nQ_11pmMtm1s',
    appId: '1:17043717885:ios:3bca9f4a3f491a32c9c894',
    messagingSenderId: '17043717885',
    projectId: 'denote-bb303',
    storageBucket: 'denote-bb303.appspot.com',
    iosClientId: '17043717885-v8tm63vkaeem8fi2fkvc73h4lj8ea1h5.apps.googleusercontent.com',
    iosBundleId: 'com.vickie.denote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn3FyXyxPzDF4KKnm2vP0nQ_11pmMtm1s',
    appId: '1:17043717885:ios:3bca9f4a3f491a32c9c894',
    messagingSenderId: '17043717885',
    projectId: 'denote-bb303',
    storageBucket: 'denote-bb303.appspot.com',
    iosClientId: '17043717885-v8tm63vkaeem8fi2fkvc73h4lj8ea1h5.apps.googleusercontent.com',
    iosBundleId: 'com.vickie.denote',
  );
}
